name: Python

on:
  push:
    branches:
    - '*'
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  check-python:

    runs-on: ubuntu-20.04

    env:
      EWOC_DAG_VERSION: "0.9.3"

    steps:
    - uses: actions/checkout@v3.1.0

    - name: Set up Python
      uses: actions/setup-python@v4.3.0
      with:
        python-version: '3.8'
  
    - name: Download ewoc_dag
      uses: robinraju/release-downloader@v1.6
      with:
        repository: "WorldCereal/ewoc_dataship"
        tag: "${{ env.EWOC_DAG_VERSION }}"
        fileName: "ewoc_dag-${{ env.EWOC_DAG_VERSION }}.tar.gz"
        token: ${{ secrets.CS_ORG_TOKEN }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install ewoc_dag-${{ env.EWOC_DAG_VERSION }}.tar.gz
        python -m pip install "boto3<2"
        python -m pip install "click<9"
        python -m pip install "lxml<5"
        python -m pip install "numpy<2"
        python -m pip install "nptyping==1.4.4"
        python -m pip install "rasterio<2"

    - name: Analysing the code with pylint
      run: |
        pip install pylint
        pylint --output-format=text $(find -type f -name "*.py" ! -path "**/venv/**")

    - name: Analysing the code with mypy
      run: |
        python -m pip install boto3-stubs
        python -m pip install lxml-stubs
        python -m pip install mypy
        python -m pip install "nptyping<2"
        mypy src

    # - name: Run tests
    #   run: python -m unittest discover -s tests

    - name: Build package
      run: |
        python -m pip install build
        python -m build

    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: distribution
        path: ./dist

  release-python:

    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: check-python

    steps:

    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: distribution
        path: ./dist

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: false
        files: |
          dist/ewoc_s2c-*.whl
          dist/ewoc_s2c-*.tar.gz
